name: checkout
on:
  push:
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actIONS/checkout@v4
      - uses: actions/CHECKout@v4
      - uses: aCTions/checkout@v4
      - uses: actions/checKOut@v4
      - uses: actIONS/cHECkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
